// Run `dotnet fsi AGENTS.fsx` from the repo root to regenerate AGENTS.md and CLAUDE.md.
#r "src/FsAgent/bin/Debug/netstandard2.0/FsAgent.dll"

open FsAgent.Prompts
open FsAgent.Writers

let agentsMd =
    prompt {
        sectionFrom "FsAgent" "knowledge/agents/fsagent.md"
        sectionFrom "General" "knowledge/agents/general.md"
        sectionFrom "Tech Stack" "knowledge/agents/tech-stack.md"
        sectionFrom "Build & Test" "knowledge/agents/build-and-test.md"
        sectionFrom "Repository Overview" "knowledge/agents/repository-overview.md"
        sectionFrom "Templating (Fue)" "knowledge/agents/templating.md"
        sectionFrom "Coding Guidelines" "knowledge/agents/coding-guidelines.md"
        sectionFrom "Git Conventions" "knowledge/agents/git-conventions.md"
    }

let content = AgentWriter.renderPrompt agentsMd (fun opts ->
    opts.IncludeFrontmatter <- false)

let header = "<!-- Generated by AGENTS.fsx — do not edit directly -->\n\n"
System.IO.File.WriteAllText("AGENTS.md", header + content)
System.IO.File.WriteAllText("CLAUDE.md", header + content)
printfn "Wrote AGENTS.md and CLAUDE.md"
